### ISSUE TITLE
Apresentação Plataforma DOT

### ISSUE THREAD

**Issue by manzettidenis** [manzettidenis/dmanzetti-todos#1]
Preparar apresentação:

- [x] Layout Home
- [ ] Orçamento Cópia
- [ ] Orçamento Venda
- [x] Defesa do produto
  - [x] Dados técnicos
  - [x] Diferenciais

- [ ] PPT Final

**Comment by manzettidenis** [comment]
Pronto.

**Comment by caiocutrim** [comment]
show
