### ISSUE TITLE
Plataforma DOT - Preparar Apresentação Tecnica Backend

### ISSUE THREAD

**Issue by manzettidenis** [manzettidenis/dmanzetti-todos#13]
Preparar uma apresentação técnica do sistema oferecido, custos mensais aproximados e expectativa de performance.

- [x] Como será garantido a eficiencia ?

- [x] Quantos usuarios ao mesmo tempo o sistema aguenta?

**Comment by manzettidenis** [comment]
@caiocutrim  como estamos?

**Comment by caiocutrim** [comment]
Estou terminando o benchmarking neste exato momento e edição do arquivo, estou terminando o benchmarking entre orientdb, mongdb, mysql e postgreesql através de uns dados colhidos na web
